version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: careerexpo_mysql
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: careerexpo

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

  api:
    build: .
    image: careerexpo-api:v1
    container_name: careerexpo_api
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/careerexpo?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
      SERVER_PORT: 8080
    volumes:
      - ./uploads/cv:/app/uploads/cv

volumes:
  mysql_data: